import type {Lesson,Visual} from "./types";

function safeName(s:string){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"_").slice(0,70)}
async function loadPptx(){const w=window as unknown as {PptxGenJS?:new()=>any};if(w.PptxGenJS)return w.PptxGenJS;await new Promise<void>((resolve,reject)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/pptxgenjs@4.0.1/dist/pptxgen.bundle.js";s.onload=()=>resolve();s.onerror=()=>reject(new Error("Không tải được bộ xuất PowerPoint"));document.head.appendChild(s)});if(!w.PptxGenJS)throw new Error("Bộ xuất PowerPoint chưa sẵn sàng");return w.PptxGenJS}

const C={navy:"17324D",coral:"FF5A5F",ink:"17283A",muted:"6D7B8A",white:"FFFFFF",line:"D9E3EA",green:"159A80"};
function addChrome(slide:any,index:number,title:string){slide.background={color:C.white};slide.addShape("rect",{x:0,y:0,w:13.333,h:.12,line:{color:C.navy,transparency:100},fill:{color:C.navy}});slide.addShape("rect",{x:.58,y:.55,w:.12,h:.58,line:{color:C.coral,transparency:100},fill:{color:C.coral}});slide.addText(title,{x:.86,y:.48,w:11.2,h:.6,fontFace:"Aptos Display",fontSize:26,bold:true,color:C.navy,margin:0,fit:"shrink"});slide.addText(String(index).padStart(2,"0"),{x:12.1,y:.55,w:.55,h:.28,fontFace:"Aptos",fontSize:10,bold:true,color:C.muted,align:"right",margin:0});slide.addShape("line",{x:.58,y:1.18,w:12.15,h:0,line:{color:C.line,width:1}})}
function visualName(v:Visual){return v.type==="variation_table"?"Bảng biến thiên":v.type==="sign_chart"?"Bảng xét dấu":v.type==="graph"?"Đồ thị hàm số":"Công thức trọng tâm"}
function addFooter(slide:any,lesson:Lesson){slide.addText(`${lesson.subject||"Toán"} · Lớp ${lesson.grade||"THPT"}`,{x:.62,y:7.15,w:5,h:.2,fontFace:"Aptos",fontSize:9,color:"8493A1",margin:0});slide.addText("LessonStudio V10",{x:10.7,y:7.15,w:2,h:.2,fontFace:"Aptos",fontSize:9,color:"8493A1",align:"right",margin:0})}
function cleanText(s:string){return String(s||"").normalize("NFC").replace(/`\s+/g," ").replace(/\$+/g,"").replace(/\\mathbb\{R\}/g,"ℝ").replace(/\\mathbb\{([A-Z])\}/g,"$1").replace(/\\infty/g,"∞").replace(/\\Leftrightarrow/g,"⇔").replace(/\\Rightarrow/g,"⇒").replace(/\\leq/g,"≤").replace(/\\geq/g,"≥").replace(/\\neq/g,"≠").replace(/\\in(?![a-z])/g,"∈").replace(/\\setminus/g,"∖").replace(/\\frac\{([^{}]+)\}\{([^{}]+)\}/g,"($1)/($2)").replace(/\^2/g,"²").replace(/\^3/g,"³").replace(/_0/g,"₀").replace(/_1/g,"₁").replace(/_2/g,"₂").replace(/\\[a-zA-Z]+/g,"").replace(/[{}]/g,"").replace(/\s+/g," ").trim()}
function addBody(slide:any,text:string,x:number,y:number,w:number,h:number){const parts=cleanText(text).split(/\s+-\s+|(?=\b\d+\.\s)/).map(x=>x.trim()).filter(Boolean).slice(0,7);if(parts.length<=1){slide.addText(parts[0]||"",{x,y,w,h,fontFace:"Aptos",fontSize:22,color:C.ink,fit:"shrink",valign:"top",margin:.08,breakLine:false});return}const runs=parts.map((p,i)=>({text:p.replace(/^\d+\.\s*/,""),options:{breakLine:true,bullet:{indent:22},hanging:4,paraSpaceAfterPt:12,bold:i===0&&parts.length>4}}));slide.addText(runs,{x,y,w,h,fontFace:"Aptos",fontSize:19,color:C.ink,fit:"shrink",valign:"top",margin:.08})}

export async function exportPptx(root:HTMLElement,lesson:Lesson,meta?:{teacher?:string;school?:string;limitSlides?:number}){
 const [PptxGenJS,{default:html2canvas}]=await Promise.all([loadPptx(),import("html2canvas")]);
 const pptx=new PptxGenJS();pptx.layout="LAYOUT_WIDE";pptx.author=meta?.teacher||"LessonStudio V10";pptx.subject="Bài giảng PowerPoint Toán THPT";pptx.title=lesson.title;pptx.company=meta?.school||"";pptx.lang="vi-VN";pptx.theme={headFontFace:"Aptos Display",bodyFontFace:"Aptos",lang:"vi-VN"};
 const cover=pptx.addSlide();cover.background={color:C.navy};cover.addShape("rect",{x:.72,y:.72,w:.18,h:5.9,line:{transparency:100},fill:{color:C.coral}});cover.addText("BÀI GIẢNG TOÁN THPT",{x:1.25,y:1.05,w:6.7,h:.35,fontFace:"Aptos",fontSize:14,bold:true,charSpacing:2.2,color:"8FD6F0",margin:0});cover.addText(lesson.title,{x:1.25,y:1.65,w:10.5,h:1.55,fontFace:"Aptos Display",fontSize:34,bold:true,color:C.white,margin:0,fit:"shrink",valign:"mid"});cover.addShape("line",{x:1.25,y:3.55,w:2.2,h:0,line:{color:C.coral,width:4}});cover.addText(`${lesson.subject||"Toán"}  |  Lớp ${lesson.grade||"THPT"}`,{x:1.25,y:3.92,w:7,h:.42,fontFace:"Aptos",fontSize:18,color:"C8D7E3",margin:0});if(meta?.teacher)cover.addText(`Giáo viên: ${meta.teacher}`,{x:1.25,y:4.55,w:7,h:.36,fontFace:"Aptos",fontSize:15,color:C.white,margin:0});if(meta?.school)cover.addText(meta.school,{x:1.25,y:5.05,w:8,h:.32,fontFace:"Aptos",fontSize:13,color:"A9BAC8",margin:0});cover.addText("V10",{x:10.5,y:5.45,w:1.5,h:.8,fontFace:"Aptos Display",fontSize:34,bold:true,color:C.coral,align:"right",margin:0});
 const stage=root.querySelector(".export-staging")||root;const articles=[...stage.querySelectorAll("article")];let slideNo=1;const limit=meta?.limitSlides||Number.POSITIVE_INFINITY;
 for(let si=0;si<lesson.sections.length&&slideNo<limit;si++){
   const section=lesson.sections[si],visuals=section.visuals||[],slide=pptx.addSlide();addChrome(slide,slideNo++,cleanText(section.heading));addFooter(slide,lesson);const nodes=[...(articles[si]?.querySelectorAll(".visual-card")||[])];
   if(!visuals.length){slide.addText(String(si+1).padStart(2,"0"),{x:.78,y:1.58,w:1.05,h:.7,fontFace:"Aptos Display",fontSize:34,bold:true,color:C.coral,margin:0});addBody(slide,section.content,1.9,1.52,10.45,4.95)}
   else{slide.addShape("roundRect",{x:.62,y:1.48,w:4.15,h:5.15,rectRadius:.06,line:{color:"D9E3EA",width:1},fill:{color:"F7FAFC"}});slide.addText("NỘI DUNG TRỌNG TÂM",{x:.88,y:1.78,w:3.6,h:.25,fontFace:"Aptos",fontSize:11,bold:true,color:C.green,charSpacing:1.2,margin:0});addBody(slide,section.content,.88,2.18,3.6,3.9);const count=Math.min(2,visuals.length);for(let vi=0;vi<count;vi++){const node=nodes[vi] as HTMLElement|undefined;if(!node)continue;const canvas=await html2canvas(node,{scale:2.5,backgroundColor:"#ffffff",useCORS:true,logging:false,scrollX:0,scrollY:0});const ratio=canvas.width/canvas.height,boxX=5.08,boxW=7.62,boxH=count===1?5.15:2.42,boxY=1.48+vi*(boxH+.3);let w=boxW-.3,h=w/ratio;if(h>boxH-.42){h=boxH-.42;w=h*ratio}slide.addText(visualName(visuals[vi]).toUpperCase(),{x:boxX+.12,y:boxY+.08,w:3.5,h:.22,fontFace:"Aptos",fontSize:9,bold:true,color:C.green,margin:0});slide.addImage({data:canvas.toDataURL("image/png"),x:boxX+(boxW-w)/2,y:boxY+.34+(boxH-.34-h)/2,w,h})}}
 }
 await pptx.writeFile({fileName:`${safeName(lesson.title)}_${Number.isFinite(limit)?"XEM_THU_10_SLIDE":"BAI_GIANG"}.pptx`});
}

export async function exportPreviewImage(root:HTMLElement,title:string){const {default:html2canvas}=await import("html2canvas");const canvas=await html2canvas(root,{scale:1.5,backgroundColor:"#ffffff",useCORS:true});const a=document.createElement("a");a.download=`${safeName(title)}_preview.png`;a.href=canvas.toDataURL("image/png");a.click()}
export function exportHtml(root:HTMLElement,title:string){const html=`<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${title.replace(/[<>&]/g,"")}</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"><style>body{font:18px Arial;color:#17283a;max-width:1100px;margin:40px auto;padding:20px}article{border:1px solid #d9e3ea;border-radius:12px;padding:24px;margin:20px 0}.visual-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.visual-card{overflow:auto;border:1px solid #d9e3ea;padding:16px}svg{max-width:100%}@media(max-width:700px){.visual-grid{grid-template-columns:1fr}}</style></head><body>${root.querySelector(".deck-preview")?.innerHTML||root.innerHTML}</body></html>`;const a=document.createElement("a");a.download=`${safeName(title)}.html`;a.href=URL.createObjectURL(new Blob([html],{type:"text/html;charset=utf-8"}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
