import type {Lesson} from "./types";
export type GeminiModel={name:string;displayName?:string;supportedGenerationMethods?:string[]};
const SYSTEM=`Bạn là engine LessonStudio V10 chuyên tạo NỘI DUNG POWERPOINT BÀI GIẢNG TOÁN THPT. Tuyệt đối không viết kế hoạch bài dạy, giáo án, mục tiêu năng lực, phẩm chất, thiết bị, tiến trình 4 bước hay rubric. Chỉ trả JSON hợp lệ theo cấu trúc {"title":string,"subject":"Toán","grade":string,"sections":[{"heading":string,"content":string,"visuals":Visual[]}]}. Tuân thủ chính xác số section người dùng yêu cầu. Mỗi section tương ứng đúng một slide và phải tự đủ nghĩa; không tạo section riêng chỉ để chứa lại hình của section trước. Nội dung mỗi section tối đa 420 ký tự, ưu tiên câu ngắn và tối đa 5 ý. Visual chỉ gồm formula, variation_table, sign_chart, graph. Mọi công thức trong content phải đặt trong cặp dấu $...$; phần còn lại viết tiếng Việt bình thường. Với variation_table: x là các mốc; derivative phải xen kẽ dấu trên khoảng và 0 tại điểm tới hạn, ví dụ 4 mốc thì ["+","0","-","0","+"]; values phải có đúng số phần tử bằng x và là giá trị hoặc giới hạn tại từng mốc. Điểm gián đoạn dùng discontinuities:[{"index":vị trí mốc,"leftValue":"+\\infty","rightValue":"-\\infty"}]. sign_chart có x là các mốc và signs xen kẽ dấu, số 0. graph dùng expression chỉ gồm x, số, +, -, *, /, ^ và ngoặc, kèm miền vẽ và các điểm đặc biệt. Không dùng Markdown fence. Không bịa dữ kiện từ tài liệu nguồn.`;
export async function scanGeminiModels(apiKey:string):Promise<GeminiModel[]>{const response=await fetch("https://generativelanguage.googleapis.com/v1beta/models",{headers:{"x-goog-api-key":apiKey}});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||"Không kiểm tra được khóa API");return (data.models||[]).filter((m:GeminiModel)=>m.name?.startsWith("models/gemini-")&&m.supportedGenerationMethods?.includes("generateContent")&&!/(image|imagen|veo|embedding|tts|audio|live)/i.test(m.name))}
export async function generateLesson(apiKey:string,model:string,prompt:string,style:string,fallbackModels:GeminiModel[]=[]):Promise<{lesson:Lesson;modelUsed:string;fallbackUsed:boolean}>{
 const choices=[model,...fallbackModels.map(x=>x.name)].filter((x,i,a)=>x&&a.indexOf(x)===i).slice(0,6);let lastError="Không có mô hình Gemini hoạt động";
 for(let i=0;i<choices.length;i++){const chosen=choices[i];try{const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/${chosen}:generateContent`,{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:SYSTEM}]},contents:[{role:"user",parts:[{text:`Phong cách trình chiếu: ${style}.\n${prompt}`}]}],generationConfig:{responseMimeType:"application/json",temperature:.18}})});const data=await response.json();if(!response.ok){lastError=data?.error?.message||`Mô hình ${chosen} không phản hồi`;if([400,401,403].includes(response.status))throw new Error(lastError);continue}const text=data?.candidates?.[0]?.content?.parts?.map((part:{text?:string})=>part.text||"").join("");if(!text){lastError=`Mô hình ${chosen} trả về nội dung trống`;continue}return {lesson:JSON.parse(text) as Lesson,modelUsed:chosen,fallbackUsed:i>0}}catch(e){lastError=e instanceof Error?e.message:lastError;if(/API key|permission|invalid|leaked/i.test(lastError))throw e}}
 throw new Error(`${lastError}. Hệ thống đã thử ${choices.length} mô hình nhưng chưa thành công.`)
}
